#language: generic

language: python

python:
  - 3.6
install:
  - pip install codecov
  - pip install coverage

script:
  - python -m unittest discover -v ./ci_play/
  - coverage run ./ci_play/test.py
  - cat index.html
  - echo "With environment variables in Travis-CI"

after_success:
  - codecov --token=449f263b-7646-4f38-bb86-a79b7fee433c
  
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "Testapp"
  env: "Testapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-586169007180"
  only_create_app_version: false
  on:
    all_branches: true
