language: generic

script:
  - cat index.html
  - echo "With environment variables in Travis-CI"

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-2"
  app: "Testapp"
  env: "Testapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-586169007180"
  only_create_app_version: false
  on:
    all_branches: true
