language: generic

script:
  - cat AWS_EB/index.html

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAYQ6TFHRGB7ZVPX3V"
  secret_access_key: "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"
  region: "us-east-2"
  app: "Testapp"
  env: "Testapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-586169007180"
  only_create_app_version: false
  on:
    all_branches: true
