
deploy:
  provider: elasticbeanstalk
  access_key_id:"AKIAYQ6TFHRGB7ZVPX3V"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "Assignment2_Group32"
  env: "Assignment2group32-env"
  bucket_name: "elasticbeanstalk-us-east-2-586169007180"
