language: generic

branches: main

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAYQ6TFHRGB7ZVPX3V"
  secret_access_key: "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"
  region: "us-east-2"
  app: "Assignment2_Part4"
  env: "Assignment2part4-env"
  bucket_name: "elasticbeanstalk-us-east-2-586169007180"
  #zip-file: "build/demo.jar"
  skip_cleanup: true
  only_create_app_version: false
